on:
  schedule:
    # UTC 23:18 (北京时间 07:18)
    #- cron: '18 23 * * *'
    # UTC 04:07 (北京时间 12:07)
    #- cron: '7 4 * * *'
    # UTC 05:47 (北京时间 13:47)
    #- cron: '47 5 * * *'
    # UTC 10:51 (北京时间 18:51)
    #- cron: '51 10 * * *'
  workflow_dispatch:
jobs:
  run_python_script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.x

      - name: 安装依赖环境
        run: |
          pip install -r requirements.txt

      - name: 获取参数
        id: get_variables
        run: |
          WORKFLOW_PATH="${{ github.workflow }}"
          WORKFLOW_NAME=$(basename $WORKFLOW_PATH)
          WORKFLOW_NAME=${WORKFLOW_NAME/\.yml/}
          WORKFLOW_NAME=${WORKFLOW_NAME/.*/}
          WORKFLOW_NAME=${WORKFLOW_NAME^^}
          echo "WORKFLOW_NAME=$WORKFLOW_NAME" >> $GITHUB_OUTPUT

      - name: 运行Python脚本
        run: |
          echo "${{ steps.get_variables.outputs.WORKFLOW_NAME }}"
          python RunTrigger.py ${{ secrets.HAMIBOT_TOKEN }} '${{ vars.HAMIBOT_PARAS }}' ${{ steps.get_variables.outputs.WORKFLOW_NAME }} ${{ vars.WECHAT_UID }}
